### ISSUE TITLE
company: back company-capf error "symbol's function definition is void -let" with args (candidate B)

### ISSUE THREAD

**Issue by stuartstein777** [racer-rust/emacs-racer#111] opened 2018-12-04 14:07 UTC
Running on Emacs on Windows,

When I try to autocomplete on

`use std::io::B` then `TAB`

I get the error 

> Company: backend company-capf error "Symbol's function definition is void: -let" with args (candidates B)

my init.el

```
(add-hook 'rust-mode-hook 'cargo-minor-mode)

(add-hook 'rust-mode-hook #'racer-mode)
(add-hook 'racer-mode-hook #'eldoc-mode)

(add-hook 'racer-mode-hook #'company-mode)
(require 'rust-mode)
(define-key rust-mode-map (kbd "TAB") #'company-indent-or-complete-common)
(setq company-tooltip-align-annotations t)
```

I have an environment variable set

`RUST_SRC_PATH = C:\Users\stuarts\.multirust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src`

I can run / build with cargo fine, all I'm missing is racer and autocomplete stuff.

I have the source the location in the RUST_SRC_PATH, it was installed via 

```
$ rustup component add rust-src
$ cargo +nightly install racer
```

Any ideas why I'm getting this error?

**Comment by Wilfred** [comment] 2018-12-05 08:56
Sounds like you don't have the dependencies of racer.el, specifically dash.el which provides -let. How did you install racer.el?

**Comment by stuartstein777** [comment] 2018-12-05 11:18
I installed it following the guide here:

https://github.com/racer-rust/emacs-racer

**Comment by Wilfred** [comment] 2018-12-10 23:57
Did you install racer.el from MELPA? Do you have dash.el? If you install dash.el, this package should work.

**Comment by Wilfred** [comment] 2021-03-07 02:22
Closing due to age. Feel free to reopen if you can reproduce.

**Closed by Wilfred** 2021-03-07 02:22 UTC
