### ISSUE TITLE
Make `racer-rust-src-path` optional, as racer can now query rustc

### ISSUE THREAD

**Issue by ccmtaylor** [racer-rust/emacs-racer#54] opened 2016-10-04 21:57 UTC
Since phildawes/racer#598, racer has a sensible default for the rust source path. Emacs-racer could rely this and make `racer-rust-src-path` (and the `RUST_SRC_PATH` environment variable) optional.

**Comment by Wilfred** [comment] 2016-10-05 11:55
Duplicate of #53 I think. Let me know if I'm mistaken.

**Comment by ccmtaylor** [comment] 2016-10-05 14:25
@Wilfred I don't think this is a duplicate. IIUC, the current behaviour falls back to `/usr/local/src/rust/src` if neither `$RUST_SRC_PATH` nor `racer-rust-src-path` are set. 

However, since phildawes/racer#598 landed, the `racer` command automatically discovers the rust-src location by calling `rustc --print sysroot`, which plays nicely with rustup's new capability to install rust sources.

My proposal is

* if `$RUST_SRC_PATH` is set, use that.
* if `racer-rust-src-path` is non-nil, use that.
* else, don't provide any source path to racer, so that it can do the right thing automatically.

This would simplify emacs-racer setup, since you don't need to configure anything if you use rustup.

**Comment by Wilfred** [comment] 2016-12-27 01:21
Done in #72.

**Closed by Wilfred** 2016-12-27 01:21 UTC
